### ISSUE TITLE
Improve stats through better RAG computation

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/edscrapers#112]
### SITUATION
The current RAG computation for the project is performed on the raw/parsed datasets rather than the the datajson which has been processed for ingestion by the harvester. The side-effect of this is : stats/RAG displayed by the dashboard are misleading/inaccurate because a healthy amount of metadata is created during datajson processing/creation which are not captured by the RAG.

### TASKS:
- [x] improve the current RAG to ensure the stats/RAG displayed are on the processed datajson
- [x] ensure improvements are easily integrated without a need to change current dashboard code
- [x] metrics/RAG computations should be available for processed and raw data
- [x] fix any bug in dashboard

### ACCEPTANCE CRITERIA
- [x] RAG has been improved/enhanced and now displays metrics of processed datajson
- [x] improved RAG code did not require dashboard code to be changed
- [x] RAG can be computed for BOTH processed and raw data
- [x] fixed dashboard bugs

Task is related to this [JIRA card](https://open-data-ed.atlassian.net/browse/OD-559) + more

**Comment by osahon-okungbowa** [comment]
Est 1.5 days
