### ISSUE TITLE
Migrate statistics and dashboard to the new infra

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#117]
We moved hosting from a manual setup on a Digital Ocean machine into a docker powered workflow setup orchestrated by Airflow.

However, the dashboard remained hosted on the old machine, where nothing else runs at the moment. We also need to retire that server as it's not relevant anymore.

**Tasks:**

- [ ] deploy the dashboard as part of the docker-compose stack
- [ ] make Airflow run statistics every time a DAG finishes successfully
  - then restarts the dash container
- [ ] close the Digital Ocean server

**Acceptance Criteria:**

- [ ] the dashboard works
- [ ] the dashboard is hosted on the new GCP server
- [ ] the dashboard numbers update with every DAG run
