### ISSUE TITLE
Add the sanitized dataset properties to the resulting data.json file

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#118]
As part of #109 we started sanitizing the data obtained by scraping. The sanitized values are stored in an extra key named `_clean_data`, which needs to be processed by the datajson transformer before the final output.

**Tasks:**

- [x] amend the datajson transformer to include the `_clean_data` values
- [x] run a harvester on a processed file to make sure everything works

**Acceptance criteria:**

- [x] the values in `_clean_data` are used in the final data.json output
