### ISSUE TITLE
Improvement & Fixes based on QA feedback

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/edscrapers#123]
### SITUATION
The codebase for Dept Ed project is actively running and producing results in our staged environment.
From the results/output being harvested, QA has been performed and points for improvements/fixes [listed here.](https://hackmd.io/bFUtzC82RDK-mO4pkwWgag?both).
We need to address the issues raised during the QA.

### TASKS
- [x] Tackle issues raised in the [QA feedback doc](https://hackmd.io/bFUtzC82RDK-mO4pkwWgag?both)

### ACCEPTANCE CRITERIA
- [x] All issues are satisfactorily addressed
- [x] project codebase still runs as expected (i.e. no new errors/bugs introduced while addressing QA feedback)

[JIRA Card](https://open-data-ed.atlassian.net/browse/OD-578)

**Comment by osahon-okungbowa** [comment]
Est 1.5 days
