### ISSUE TITLE
Discovery Issue: links between datasets/resources across offices

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/edscrapers#139]
## Situation/Description

For the Dept of Ed scraping exercise, each office is being scraped independently (with its own set of URLs). It is assumed with this independent approach, that there are (little or) no links to datasets across offices. This assumption also extends to dataset resources. We need to investigate these assumptions

## Tasks

We need to investigate this:
- [ ] are links to datasets across offices?
- [ ] if links to datasets across offices exist, identify the offices
- [ ] are links to resources across offices?
- [ ] if links to resources across offices exist, identify the offices
- [ ] write a script that can be run to generate output that answers these questions

## Acceptance Criteria
- [ ] there is a script that generates output(s) to identify if links to datasets/resources exist across offices
