### ISSUE TITLE
Refactoring the compare module

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/edscrapers#143]
## Description/Situation

We have a `compare` module which is used to firstly compare stats between Datopian/Air, but it also includes some useful stats which the Dashboard and the `stats` module are dependent on. 
We are no longer interested in running any comparison with AIR - so the compare module has been deprecated/marked for removal.

We need to incorporate the useful aspects (the functionality which Dashboard and stats module are dependent on) of the deprecated compare module into the edscrapers namespace so that the dashboard and stats module don't break

**NOTE:** the AIR comparison page on the dashboard is being removed, so it is not to necessary for the `compare` module to work with it

## Task
- [x] remove all aspects of the compare module that deals with comparing Datopian & AIR data
- [x] ensure the refactored compare module lives inside the edscrapers namespace
- [x] the `compare` module must still support all necessary functionality for the stats module
- [x] the `compare` module must still support all necessary functionality for the dashboard page

## Acceptance Criteria
- [x] the `compare` module runs successfully and generates numbers
- [x] the stats module works with the refactored `compare` without errors
- [x] the dashboard works with the refactored `compare` without errors
- [x] no need for the `eds compare` command to be run in order to bootup the dashboard
- [x] QA by Osahon
