### ISSUE TITLE
Improve scraper for Institute of Education Sciences (Phase 2)

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/edscrapers#167]
During phase 1 we created a functional scraper for crawling and parsing data from this office. The scraped data was successfully ingested into the data portal. 

For phase 2, we need to improve the quality of metadata and data-content for the datasets being generated by the scraper.

https://ies.ed.gov/

Acceptance Criteria
* [x] we have marked improvement in the quality of metadata and data-content of datasets produced by the scraper.
* [x] the improved quality datasets are visible on the data portal

## Tasks

* [x] Ensure datasets produced have a description metadata
* [x] Ensure datasets have a publisher metadata
* [x] Improve other metadata (use defaults where available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-638?atlOrigin=eyJpIjoiMjlhMWZlODAwMGRhNDkxNmIwMDdkZmNkMDUxMWQ0M2EiLCJwIjoiaiJ9)

**Comment by higorspinto** [comment]
Related PRs:

https://github.com/CivicActions/edscrapers/pull/201
https://github.com/CivicActions/edscrapers/pull/173
