### ISSUE TITLE
P6 Metadata (OPEPD): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/edscrapers#63]
Description: Improve metadata quality from P6 Office of Planning, Evaluation and Policy Development parser

### TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

### Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-542?atlOrigin=eyJpIjoiNGExMmZhYTY4YzczNGM3NmJlMmZjOGJlMjY5NDUzMzQiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1.5 day (resources with file names in _strange_ locations)
