### ISSUE TITLE
P7 Metadata (OESE): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/edscrapers#64]
Description: Improve metadata quality from P7 Office of Elementary and Secondary Education parser

### TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

### Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-543?atlOrigin=eyJpIjoiMGFiNzlmYzQxZDUxNDJmN2JmMzJiNmRiOWMwOTMzODUiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 Day
