### ISSUE TITLE
Update Tech Spec to reflect metrics and dashboard changes

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/edscrapers#82]
### SITUATION
The Dept Ed Scraping project has evolved rapidly and there is critical need to evaluate and measure the progress of the project. 
Although quantitative measurements and reporting was not part of the original tech spec for the project, we now need adequate specs on how to effectively and easily capture and report some quantitative measures which benchmark project progress internally and externally

### TASKS

- [x] Analyse the problem and identify adequate quantitative metrics and reports for the project

- [x] Design a tech spec which allows for the rapid gathering and reporting of identified significant metrics

- [x] Design tech spec to also include easy to understand visualisations of metrics

- [x] Design tech to include periodic reports/trends feature

### ACCEPTANCE CRITERIA
- [x] Tech spec includes agreed critical metrics which can be clear indicators of project progress
- [x] Tech spec includes an automated process of metrics gathering 
- [x] Tech spec includes an internal/external channel (may be a dashboard) for reporting and visualising gathered metrics

**Comment by nightsh** [comment]
ETA 2-3 hours to document everything.
