### ISSUE TITLE
Automate the scraping pipelines

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#95]
**The situation**

The `edscrapers` module has an increasing number of scrapers. In order to produce 
an output usable by CKAN, each scraper needs to run, then its output to be 
deduplicated using a simple universal script, then the deduplication result goes 
into a datajson transformer. In addition to this, scraping results are also subject 
of a real time statistics module and public HTTP dashboard, which needs updating 
every time there are new results.

Having to operate all the system manually is cumbersome and could lead to human 
errors due to its sequential and multithreaded nature.

It also costs time to monitor, run and type all the commands needed to operate 
each step for each scraper (via SSH / terminal access).

The consensus was that we wouldn't develop pipelines, and focus on the scraping 
instead. At the moment, we have a number of steps, but no pipeline to glue them 
and standardize logging / reporting.

**Analogy**

A car washing company has 10 stalls and one employee operating them. Normally 
one or two cars come at once, but there are times when more or all the stalls 
are full. Each car needs to be washed following a specific sequence, and not 
respecting that could void the process partially or totally.

Would it be worth for the car wash to automate its stalls, so all the operations 
are carried out automatically and quality is ensured without depending on a human 
executing multiple sequences (each in a different stage) at once?

Would it increase the efficiency long term? Mid term? Short term?

Would it prevent otherwise unnoticed and unnoticeable errors leading to poor 
results? What about finding out what went wrong when problems are spotted 
(debugging)?

**The proposed approach**

Having a pipeline framework and manager that could run all these steps for us 
would have some benefits:

* standard errors / progress monitoring
* web UI, users etc.
* we don't have to glue things together in improvised pipelines
* portability and ability to schedule / trigger pipelines

Airflow is the best candidate for this, according to 
[the analysis](https://hackmd.io/GSDrhv1DRG6kGynBZjsXXQ) we have already made.

The steps are also documented in the doc linked above.

**Tasks**

* [x] Bootstrap an Airflow instance
* [x] Create the pipelines for each scraper
* [x] Test if it runs properly
* [x] Make sure dashboard reads from the right source

**Acceptance criteria**

* [x] We have an Airflow instance running the scrapers
* [x] Dashboard is updating
* [ ] Pipelines are running automatically
