### ISSUE TITLE
Change data quality assessment to measure datajson output

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#99]
Currently we are generating a RAG summary based on a data quality analysis, which uses a weighted scoring system.

The problem is that we are measuring the quality of the scraped data, and not the quality of the data that ends up in CKAN. We should be assessing the quality of the items in the final datajson output.

**Tasks:**

- [x] Add a new feature to the RAG summary to switch measuring target from JSON files to data.json transformer output
  - [x] Keep the existing implementation in case we want to compare before/after datajson phase
- [x] Make the dashboard use the new scores

**Acceptance criteria:**

- [x] RAG transformer measures datajson output
- [x] Dashboard shows datajson assessment
